Self study question

Find the diffrent between python list and Numpy


Write about numpy
The python package NumPy, which stand for "Numerical PythoN"

In [3]:
print("hello AI/ML")
print ("hello Narendra")

hello AI/ML
hello Narendra


In [10]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/2d/57/8aeaf160312f7f489dea47ab61e430b5cb051f59a98ae68b7133ce8fa06a/numpy-2.3.5-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 131.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 249.7 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.8 MB 3.2 MB/s eta 0:00:04
    --------------------------------------- 0.3/12.8 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import numpy as np

In [12]:
print(np.__version__)

2.3.5


In [13]:
l1 = [1, 2, 3, 4, 5]
print(l1)

[1, 2, 3, 4, 5]


In [14]:
l1

[1, 2, 3, 4, 5]

In [15]:
x= np.array(l1)

In [16]:
x

array([1, 2, 3, 4, 5])

In [17]:
x.dtype

dtype('int64')

In [ ]:
x= np.array([1,2,3,4,5])
print(x)

In [26]:
z=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print (z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [28]:
a=np.ones((5,5),dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
a=np.full((5,5),10)
a

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [30]:
a=np.eye(5,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
a=7*np.eye(5,5,dtype=int)
a

array([[7, 0, 0, 0, 0],
       [0, 7, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 7]])

In [32]:
a.size

25

In [36]:
a.dtype


dtype('int64')

In [37]:
z.shape

(1, 4, 3)

In [39]:
a.shape

(5, 5)

In [40]:
x


array([1, 2, 3, 4, 5])

In [42]:
x.min()

np.int64(1)

In [43]:
x.max()

np.int64(5)

In [44]:
x.argmax()

np.int64(4)

In [47]:
x.argmin()

np.int64(0)

In [48]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
b= np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [50]:
c=np.add(a,b)
print(c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [51]:
d=np.subtract(a,b)
print(d)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [52]:
m=np.multiply(a,b)
print(m)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [53]:
f=np.divide(a,b)
print(f)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [54]:
a=np.random.randint(5,30,(2,2))
b=np.random.randint(6,30,(2,2))
np.add(a,b )

array([[35, 36],
       [47, 29]], dtype=int32)

Indexing is the process of accesing a single elemrnt from a sequence using its positions or index

it retrieves a single element at a specific position.

Python uses a zero-based indexing (0 is the first elements).

Negative indexing allows access from the end of the structure.

In [55]:
x


array([1, 2, 3, 4, 5])

In [56]:
x[2]
x[-1]

np.int64(5)

In [57]:
x[2]

np.int64(3)

Slicing: Extracts a sublist (portion ) of elements within a specified range

In [58]:
x[:]

array([1, 2, 3, 4, 5])

In [59]:
x[0:]

array([1, 2, 3, 4, 5])

In [60]:
x[5:]

array([], dtype=int64)

In [62]:
x[2:5]=99

In [63]:
x

array([ 1,  2, 99, 99, 99])

In [64]:
x[:]=100

In [65]:
x

array([100, 100, 100, 100, 100])

In [66]:
m=np.random.randint(1,50,10)
m

array([37, 49, 27, 22, 47, 28, 18, 15, 44, 20], dtype=int32)

In [69]:
s=np.flip(m)
s

array([20, 44, 15, 18, 28, 47, 22, 27, 49, 37], dtype=int32)

In [72]:
m=np.flip(m)
m

array([20, 44, 15, 18, 28, 47, 22, 27, 49, 37], dtype=int32)