Self study question

Find the diffrent between python list and Numpy


Write about numpy
The python package NumPy, which stand for "Numerical PythoN"

In [3]:
print("hello AI/ML")
print ("hello Narendra")

hello AI/ML
hello Narendra


In [10]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/2d/57/8aeaf160312f7f489dea47ab61e430b5cb051f59a98ae68b7133ce8fa06a/numpy-2.3.5-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 131.3 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.9 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 249.7 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.8 MB 3.2 MB/s eta 0:00:04
    --------------------------------------- 0.3/12.8 MB 3.3 MB/s eta 0:00:04
   -- ------------------------------


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import numpy as np

In [12]:
print(np.__version__)

2.3.5


In [13]:
l1 = [1, 2, 3, 4, 5]
print(l1)

[1, 2, 3, 4, 5]


In [14]:
l1

[1, 2, 3, 4, 5]

In [15]:
x= np.array(l1)

In [16]:
x

array([1, 2, 3, 4, 5])

In [17]:
x.dtype

dtype('int64')

In [ ]:
x= np.array([1,2,3,4,5])
print(x)

In [26]:
z=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print (z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [28]:
a=np.ones((5,5),dtype=int)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
a=np.full((5,5),10)
a

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [30]:
a=np.eye(5,5,dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
a=7*np.eye(5,5,dtype=int)
a

array([[7, 0, 0, 0, 0],
       [0, 7, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 7]])

In [32]:
a.size

25

In [36]:
a.dtype


dtype('int64')

In [37]:
z.shape

(1, 4, 3)

In [39]:
a.shape

(5, 5)

In [40]:
x


array([1, 2, 3, 4, 5])

In [42]:
x.min()

np.int64(1)

In [43]:
x.max()

np.int64(5)

In [44]:
x.argmax()

np.int64(4)

In [47]:
x.argmin()

np.int64(0)

In [48]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
b= np.array([[9,8,7],[6,5,4],[3,2,1]])
print(a)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [50]:
c=np.add(a,b)
print(c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [51]:
d=np.subtract(a,b)
print(d)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [52]:
m=np.multiply(a,b)
print(m)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [53]:
f=np.divide(a,b)
print(f)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [54]:
a=np.random.randint(5,30,(2,2))
b=np.random.randint(6,30,(2,2))
np.add(a,b )

array([[35, 36],
       [47, 29]], dtype=int32)

Indexing is the process of accesing a single elemrnt from a sequence using its positions or index

it retrieves a single element at a specific position.

Python uses a zero-based indexing (0 is the first elements).

Negative indexing allows access from the end of the structure.

In [55]:
x


array([1, 2, 3, 4, 5])

In [56]:
x[2]
x[-1]

np.int64(5)

In [57]:
x[2]

np.int64(3)

Slicing: Extracts a sublist (portion ) of elements within a specified range

In [58]:
x[:]

array([1, 2, 3, 4, 5])

In [59]:
x[0:]

array([1, 2, 3, 4, 5])

In [60]:
x[5:]

array([], dtype=int64)

In [62]:
x[2:5]=99

In [63]:
x

array([ 1,  2, 99, 99, 99])

In [64]:
x[:]=100

In [65]:
x

array([100, 100, 100, 100, 100])

In [66]:
m=np.random.randint(1,50,10)
m

array([37, 49, 27, 22, 47, 28, 18, 15, 44, 20], dtype=int32)

In [69]:
s=np.flip(m)
s

array([20, 44, 15, 18, 28, 47, 22, 27, 49, 37], dtype=int32)

In [72]:
m=np.flip(m)
m

array([20, 44, 15, 18, 28, 47, 22, 27, 49, 37], dtype=int32)

Tutorial :2 Explore pandas library to analyze and manipulate data.

pandas is an open-source Library for real world data analysis in python

it is built on top of NumPy

Using pandas, data can be cleaned, transformed, manipulated, and analyzed.

The basic data structure of pandas are Series and DataFrame.

1. Series object : Series is a one dimension labeled array.

2. DataFrame : A DataFrame in pandas is a two-dimension, tabular data structure. its consists of rows and columns.
Columns represent different features.
Rows represent different features.
Rows represent record of entries.
Index means label of row.

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/86/41/585a168330ff063014880a80d744219dbf1dd7a1c706e75ab3425a987384/pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/81/c4/34e93fe5f5429d7570ec1fa436f1986fb1f00c3e0f43a589fe2bbcd22c3f/pytz-2025.2-py2.py3-none-any.whl.metadata
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/c7/b0/003792df09decd6849a5e39c28b513c06e84436a54440380862b5aeff25d/tzdata-2025.3-py2.py3-none-any.whl.metadata
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.2/11.0 MB 6.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/11.0 MB 7.0 MB/s eta 0:00:02
   --- ------------------------------------ 0.9/11.0 MB 8.0 MB/s eta 0:00:02


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import pandas as np

homework :find  out the diffrent between list and numpy array and pandas series


In [6]:
a=np.array([1,2,3,4,5])
type(a)

pandas.core.arrays.integer.IntegerArray

In [8]:
s1=pd.Series([10,20,30,40,50])
type(s1)

pandas.core.series.Series

In [9]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
s2=pd.Series([10,20,30,40,50], ['A','B','C','D','E'])
s2.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [11]:
s2.values

array([10, 20, 30, 40, 50])

In [13]:
data=[{'name':'Sams','Marks':80},
      {'name':'Raju','Marks':90},
      {'name':'Narendra','Marks':75}]

In [15]:
f1=pd.DataFrame(data)
f1

name  Marks
0      Sams     80
1      Raju     90
2  Narendra     75

In [16]:
type(f1)

pandas.core.frame.DataFrame

In [17]:
type(data)

list

In [18]:
f1.isna()

name  Marks
0  False  False
1  False  False
2  False  False

In [20]:
f1.isna().sum()

name     0
Marks    0
dtype: int64

In [24]:
student=pd.read_excel("book.ods")
student

ImportError: Missing optional dependency 'odfpy'.  Use pip or conda to install odfpy.

In [22]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ---------------- ----------------------- 102.4/250.9 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 2.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [32]:
import pandas as pd

student = pd.read_excel("book.ods", engine="odf")
student


Name  age  rollno
0  narendra   20      45
1   shivesh   18      21
2       ram   16      45
3      raju   32      14

In [33]:
pip install odfpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [28]:
iris=pd.read_csv("iris.csv")
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [35]:
iris.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [39]:
iris.head(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [40]:
iris.tail(10)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
140  141            6.7           3.1            5.6           2.4   
141  142            6.9           3.1            5.1           2.3   
142  143            5.8           2.7            5.1           1.9   
143  144            6.8           3.2            5.9           2.3   
144  145            6.7           3.3            5.7           2.5   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [42]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [44]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [46]:
iris=iris.rename(columns={'SepalLengthCm':'Sepal_Length', 'SepalWidthCm':'Sepal_Width', 'PetalLengthCm':'Petal_Length', 'PetalWidthCm':'Petal_Width'})
iris

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width         Species
0      1           5.1          3.5           1.4          0.2     Iris-setosa
1      2           4.9          3.0           1.4          0.2     Iris-setosa
2      3           4.7          3.2           1.3          0.2     Iris-setosa
3      4           4.6          3.1           1.5          0.2     Iris-setosa
4      5           5.0          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
145  146           6.7          3.0           5.2          2.3  Iris-virginica
146  147           6.3          2.5           5.0          1.9  Iris-virginica
147  148           6.5          3.0           5.2          2.0  Iris-virginica
148  149           6.2          3.4           5.4          2.3  Iris-virginica
149  150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 6 columns]

In [48]:
iris.columns

Index(['Id', 'Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width',
       'Species'],
      dtype='object')

In [49]:
cat=iris['Species'].unique()
cat

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [51]:
iris.replace({'Species':{'Iris-setosa':'Setosa'}}, inplace=True)    
iris.replace({'Species':{'Iris-versicolor':'Versicolor'}}, inplace=True)
iris.replace({'Species':{'Iris-virginica':'Virginica'}}, inplace=True)

In [55]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Id            150 non-null    int64  
 1   Sepal_Length  150 non-null    float64
 2   Sepal_Width   150 non-null    float64
 3   Petal_Length  150 non-null    float64
 4   Petal_Width   150 non-null    float64
 5   Species       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [57]:
iris.describe()

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count  150.000000    150.000000   150.000000    150.000000   150.000000
mean    75.500000      5.843333     3.054000      3.758667     1.198667
std     43.445368      0.828066     0.433594      1.764420     0.763161
min      1.000000      4.300000     2.000000      1.000000     0.100000
25%     38.250000      5.100000     2.800000      1.600000     0.300000
50%     75.500000      5.800000     3.000000      4.350000     1.300000
75%    112.750000      6.400000     3.300000      5.100000     1.800000
max    150.000000      7.900000     4.400000      6.900000     2.500000

In [61]:
iris[['Sepal_Length', 'Sepal_Width']].head(10)

Sepal_Length  Sepal_Width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6
5           5.4          3.9
6           4.6          3.4
7           5.0          3.4
8           4.4          2.9
9           4.9          3.1

In [65]:
def yes_no(Sepal_Length):
    return 'YES' if Sepal_Length >= 5 else 'NO'

# apply function to create new column
iris['Result'] = iris['Sepal_Length'].apply(yes_no)

iris


Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species  \
0      1           5.1          3.5           1.4          0.2     Setosa   
1      2           4.9          3.0           1.4          0.2     Setosa   
2      3           4.7          3.2           1.3          0.2     Setosa   
3      4           4.6          3.1           1.5          0.2     Setosa   
4      5           5.0          3.6           1.4          0.2     Setosa   
..   ...           ...          ...           ...          ...        ...   
145  146           6.7          3.0           5.2          2.3  Virginica   
146  147           6.3          2.5           5.0          1.9  Virginica   
147  148           6.5          3.0           5.2          2.0  Virginica   
148  149           6.2          3.4           5.4          2.3  Virginica   
149  150           5.9          3.0           5.1          1.8  Virginica   

    Result  
0      YES  
1       NO  
2       NO  
3       NO  
4      YES  
..     ...  
145    YES  
146    YES  
147    YES  
148    YES  
149    YES  

[150 rows x 7 columns]

In [71]:
iris.drop('Result', axis=1, inplace=True)
iris.head()


KeyError: "['Result'] not found in axis"

In [69]:
iris.columns

Index(['Id', 'Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width',
       'Species'],
      dtype='object')

In [70]:
iris

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0      1           5.1          3.5           1.4          0.2     Setosa
1      2           4.9          3.0           1.4          0.2     Setosa
2      3           4.7          3.2           1.3          0.2     Setosa
3      4           4.6          3.1           1.5          0.2     Setosa
4      5           5.0          3.6           1.4          0.2     Setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  Virginica
146  147           6.3          2.5           5.0          1.9  Virginica
147  148           6.5          3.0           5.2          2.0  Virginica
148  149           6.2          3.4           5.4          2.3  Virginica
149  150           5.9          3.0           5.1          1.8  Virginica

[150 rows x 6 columns]

the .iloc indexing is primary used for integer-location based indexing,
#allowing you to access a group of rows and columns by there numerical insexing

In [74]:
iris.iloc[0]

Id                   1
Sepal_Length       5.1
Sepal_Width        3.5
Petal_Length       1.4
Petal_Width        0.2
Species         Setosa
Name: 0, dtype: object

In [75]:
iris.iloc[51,56:1]

Series([], Name: 51, dtype: object)

In [77]:
iris.iloc[51:56:1]

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species
51  52           6.4          3.2           4.5          1.5  Versicolor
52  53           6.9          3.1           4.9          1.5  Versicolor
53  54           5.5          2.3           4.0          1.3  Versicolor
54  55           6.5          2.8           4.6          1.5  Versicolor
55  56           5.7          2.8           4.5          1.3  Versicolor

In [78]:
iris.iloc[51:56:]

Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species
51  52           6.4          3.2           4.5          1.5  Versicolor
52  53           6.9          3.1           4.9          1.5  Versicolor
53  54           5.5          2.3           4.0          1.3  Versicolor
54  55           6.5          2.8           4.6          1.5  Versicolor
55  56           5.7          2.8           4.5          1.3  Versicolor