In [10]:
print("hello narendra")

hello narendra


In [ ]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np

In [13]:
print (np.__version__)

2.3.5


creat an array from list
1D
2D
3D

In [14]:
array_1d=np.array([1,2,3,3])
print("creat 1d array:",array_1d)

creat 1d array: [1 2 3 3]


In [ ]:
array_2d=np.array([[1,1,4],[7,8,9]])
print("creat 2d array:",array_2d)

creat 2d array: [[1 1 4]
 [7 8 9]]


In [16]:
array_3d=np.array([[[1,4,5],[7,8,9],[9,8,7]]])
print("creat 3d array :",array_3d)

creat 3d array : [[[1 4 5]
  [7 8 9]
  [9 8 7]]]


list vs numpy array


In [21]:
py_list=[1,7,6,9,10,45]
print("print the list:",py_list)

print the list: [1, 7, 6, 9, 10, 45]


In [22]:
py_list*2

[1, 7, 6, 9, 10, 45, 1, 7, 6, 9, 10, 45]

In [25]:
 np_array=np.array([1,2,3])
 print(np_array*2)
 
 print(np_array*3)

[2 4 6]
[3 6 9]


In [26]:
import time

In [27]:
start=time.time()

In [29]:
py_list=[i*2 for i in range (10000000)]
print("\n list operation time :",time.time ()-start)


 list operation time : 154.3274233341217


In [32]:
start =time.time()
np_array=np.array(100000000)*2
print("\n Numpy operation time :",time.time ()-start)


 Numpy operation time : 0.0


Creat an arra from Scratch


In [33]:
zeros=np.zeros((4,4))
print("4*4 Zeros materx:\n",zeros)

4*4 Zeros materx:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
zeros =np.zeros((2,4))
print ("2*4 zeros materx:\n",zeros)

2*4 zeros materx:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
ones=np.ones((4,4))
print ("4*4 ones materx:\n",ones)

4*4 ones materx:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
ones=np.ones((2,4))
print ("2*4 ones materx:\n",ones)

2*4 ones materx:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
full =np.full((4,4),6)
print ("print full materix:\n",full)

print full materix:
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [40]:
full =np.full((3,4),0)
print ("print full materix:\n",full)

print full materix:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
